name: haldeki_tedarikci_web
description: Haldeki Tedarikçi için tam web tabanlı Flutter Web arayüzü
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.0
  http: ^1.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  dio: ^5.9.0
  shared_preferences: ^2.2.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  file_picker: ^8.0.5
  cached_network_image: ^3.4.0
  data_table_2: 2.5.15
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/motor.png
    - assets/logo.png
    - assets/haldeki_logo.png
    - assets/logo/haldeki_logo.png
    - assets/logo/haldeki_logo_icon.png
